services:
  api1: &api
    build: 
      context: .
      target: base
    container_name: api1
    environment:
      - RUBY_YJIT_ENABLE=1
      - DB_POOL_SIZE=10
    command: rackup
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    depends_on:
      - postgres

  api2: 
    <<: *api
    container_name: api2

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  nginx:
    image: nginx 
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9999:9999
    depends_on:
      - api1
      - api2

volumes:
  rubygems:
