services:
  api1: &api
    build: 
      context: .
      target: base
    container_name: api1
    environment:
      - RUBY_YJIT_ENABLE=1
      - DB_POOL_SIZE=5
    command: rackup
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '150MB'

  api2: 
    <<: *api
    container_name: api2

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '200MB'

  nginx:
    image: nginx 
    container_name: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9999:9999
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '50MB'

volumes:
  rubygems:
